### ISSUE TITLE
Typo in class name in java-fix-method-passing-value

### ISSUE THREAD

**Issue by barthon-b** [ByteLegend/ByteLegend#107]
Hi,

Quest README.md in [java-fix-method-passing-value](https://github.com/ByteLegendQuest/java-fix-method-passing-value) seems to be erroneously referring to Main instead of Home. See this PR: https://github.com/ByteLegendQuest/java-fix-method-passing-value/pull/9/files

(the PR can't be merged as the system is treating it as a quest answer submission)

**Comment by jaryarbn** [comment]
If you want to contribute to this repository, please select the dev branch.
![image](https://user-images.githubusercontent.com/58287154/147251504-08a50648-497b-4f6b-a9c1-a3db3d6d4591.png)

**Comment by blindpirate** [comment]
Fixed in https://github.com/ByteLegendQuest/java-fix-method-passing-value/commit/22b08508fe1cc1bab125dfd4b3a558db56b70afa

Thanks @barthon-b @jaryarbn
