### ISSUE TITLE
无法通过以下关卡：安装Java

### ISSUE THREAD

**Issue by kiryucocorip** [ByteLegend/ByteLegend#112]
字面意思。

终端输出内容：
root@RANDOMIZED /randomized# java --version
java 17.0.2 2022-01-18 LTS
Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)

**Comment by blindpirate** [comment]
是这里的这个正则有问题，你愿意提交一个PR帮我们改正么？https://github.com/ByteLegend/game-data/blob/9b44cf710d69b733e64425adfac82fea07c515e2/JavaIslandNewbieVillagePub/missions/install-java.yml#L20

**Comment by blindpirate** [comment]
Java 17之后`java -version`的格式似乎有所改变

**Comment by kiryucocorip** [comment]
> Java 17之后`java -version`的格式似乎有所改变

好像并不是这样，Linux的Java运行此命令时会缺少“version”这个词，就是这个词的缺失导致第一关卡关
这时候只需要这么写就可以通过该关卡：
java version 17.0.2 2022-01-18 LTS
Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)

由于我个人不会写yml，所以我尝试删除了正则中的“version”和一个空格

**Comment by gtn1024** [comment]
我比较好奇你使用的是哪个vendor的Java？

**Comment by blindpirate** [comment]
你可以使用`jshell`看vendor：

```
$ jshell
|  Welcome to JShell -- Version 11.0.11
|  For an introduction type: /help intro

jshell> System.getProperty("java.vendor")
$1 ==> "AdoptOpenJDK"
```
