### ISSUE TITLE
无法通过”类与包“这个障碍

### ISSUE THREAD

**Issue by yunghf** [ByteLegend/ByteLegend#122]
三个塔的挑战都通过了，但路障没有打开，无法通过。请问如何解决。

ps 这个项目很棒，我正想学习ava，感谢您的付出。

**Comment by blindpirate** [comment]
你走到路障前面点击它一下？不然刷新一下页面？

**Comment by yunghf** [comment]
![屏幕截图 2022-03-23 110428](https://user-images.githubusercontent.com/24445135/159615928-6b7ebeed-d3a1-4d6c-99b4-85fbb6991a7c.jpg)
都无效

**Comment by blindpirate** [comment]
请你在首页的“联系 & 关于”里加QQ群或者Discord？

**Comment by blindpirate** [comment]
我看到你只是完成了挑战，还没有摧毁防御塔。你需要走到防御塔下按上面的按钮摧毁之才可以。
