### ISSUE TITLE
Add timeout limit for each job 

### ISSUE THREAD

**Issue by SaraadKun** [ByteLegend/ByteLegend#139]
I wrote a dead loop in the game, as the pic shows, and submit the answer, then it blocked.
<img width="839" alt="image" src="https://user-images.githubusercontent.com/35584589/181920222-3de32b2b-73ef-40e0-881b-8187a734e9cf.png">
I saw the PR in the repo of this game stage, the workflow are blocking on the "Verify" stage for nearly one hour, and I didn't found anyway to stop it.
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/35584589/181920494-113970d0-bbec-4688-8afe-fdb426aaef49.png">
So I suggest that there should be a timeout limit for every job in repos, like 5 or  10 minutes.

**Comment by blindpirate** [comment]
Thanks for the suggestion. This is done. All checks have 10m timeout now.
