### ISSUE TITLE
Could not get a repository handle for submodule 'server'

### ISSUE THREAD

**Issue by Drincann** [ByteLegend/ByteLegend#14]
![image](https://user-images.githubusercontent.com/53897259/120488441-5b361780-c3e9-11eb-956e-900210554641.png)

第一次运行，提示我需要拉 'game-data' 子模块。

拉了 'game-data' 之后再次运行，提示如上图，于是试图拉 'server'，但是没有成功。

**Comment by blindpirate** [comment]
加`--stacktrace`，贴stacktrace。

**Comment by Drincann** [comment]
> 加`--stacktrace`，贴stacktrace。

![image](https://user-images.githubusercontent.com/53897259/120489494-427a3180-c3ea-11eb-8910-3b93df18abc8.png)

**Comment by blindpirate** [comment]
Closed by https://github.com/ByteLegend/ByteLegend/commit/76de3b9d7b9e62a77a1c23bf333d200d798acdd4

**Comment by blindpirate** [comment]
Thanks for reporting!

**Comment by Drincann** [comment]
拉下最新代码后再次尝试运行，在启动后端服务后，抛出了异常 ` java.io.FileNotFoundException: B:\workspace\Git\ByteLegend\utils\build\game-resources\map\hierarchy.yml`。

![image](https://user-images.githubusercontent.com/53897259/120509406-0c917900-c3fb-11eb-9c04-ec5214ce4b01.png)

我尝试在该目录下寻找该文件，发现并不存在 `.\utils\build\game-resources`  目录，但在一个类似目录下存在所需文件 `.\utils\build\game-resources-dev/map/hierarchy.yml` 下图：

![image](https://user-images.githubusercontent.com/53897259/120509958-90e3fc00-c3fb-11eb-87fc-e4374e91f711.png)

![image](https://user-images.githubusercontent.com/53897259/120510377-f1733900-c3fb-11eb-9860-bb368b714272.png)

我尝试直接拷贝了 `.\utils\build\game-resources-dev` 到当前目录并更名为 `game-resources`。

![image](https://user-images.githubusercontent.com/53897259/120510897-73fbf880-c3fc-11eb-8f2b-ed1bc38bb36e.png)

尝试再次运行：

![image](https://user-images.githubusercontent.com/53897259/120510605-2b443f80-c3fc-11eb-8e9b-96846258d2d6.png)

好像卡在了某个步骤，但在本地 8080 端口已经开启了相关服务，可以正常访问。
