### ISSUE TITLE
好喜欢这种寓教于乐的项目！ 

### ISSUE THREAD

**Issue by HydroCyanicum** [ByteLegend/ByteLegend#145]
我正在通过游戏学习编程，在爪哇岛的(BJ, 94)坐标处打开
宝箱，输入我的邀请码 loxE0jKFmsPIbHTDV3，你和我都可以获得500金币，
快来 https://bytelegend.com 字节传说加入我吧！

**Comment by HydroCyanicum** [comment]
很抱歉，第一次用github，不知道new issue是重新开一个串而不是跟帖，发错地方了但删不掉。

**Comment by jaryarbn** [comment]
可以关掉issue，https://docs.github.com/en/issues/tracking-your-work-with-issues/closing-an-issue

**Comment by HydroCyanicum** [comment]
感谢！学习了。
