### ISSUE TITLE
我的邀请码

### ISSUE THREAD

**Issue by xuchang19** [ByteLegend/ByteLegend#148]
我正在通过游戏学习编程，在爪哇岛的(BJ, 94)坐标处打开
宝箱，输入我的邀请码 leZpIueqbfM11，你和我都可以获得500金币，
快来 https://bytelegend.com 字节传说加入我吧！

**Comment by guakun01** [comment]
我正在通过游戏学习编程，在爪哇岛的(BJ, 94)坐标处打开
宝箱，输入我的邀请码 lqn68R4LruE，你和我都可以获得500金币，
快来 https://bytelegend.com 字节传说加入我吧！
