### ISSUE TITLE
在「使用PR修复Bug」关卡中 挑战界面崩溃

### ISSUE THREAD

**Issue by QSlotus** [ByteLegend/ByteLegend#151]
![capture_20221220175322750](https://user-images.githubusercontent.com/109905194/208638329-027317ae-57f1-4312-b7e9-8dae0313aa62.jpg)
在「使用PR修复Bug」关卡中挑战界面崩溃，请问该问题如何解决

**Comment by blindpirate** [comment]
请换Chrome重试。
