### ISSUE TITLE
0金币的教程点击获取后无反应

### ISSUE THREAD

**Issue by QSlotus** [ByteLegend/ByteLegend#152]
如题

**Comment by blindpirate** [comment]
请描述的更详细一点，最好有相应的环境或者全屏截图或者录屏。

**Comment by QSlotus** [comment]
环境：Google Chrome 108.0.5359.125 (正式版本) （64 位） (cohort: Stable) 

录屏：https://user-images.githubusercontent.com/109905194/209078010-17a77f2a-2b91-45d4-a8d9-b768fb70d230.mp4

**Comment by blindpirate** [comment]
因为教程不存在，还没写。

<img width="388" alt="image" src="https://user-images.githubusercontent.com/12689835/209078756-06386afe-53d8-47f0-bb2d-861c6dd021bb.png">
