### ISSUE TITLE
Brave people board cannot show all people

### ISSUE THREAD

**Issue by chengww5217** [ByteLegend/ByteLegend#26]
It seems that the **Brave people board** cannot show all people.
This is a screenshot of my computer in the game.

![image](https://user-images.githubusercontent.com/34536334/130178530-0a29ca78-bc20-4e3b-b5e9-89defe9e4f95.png)

But you can see there are some people in the bottom, we cannot see them.

The **Brave people board** origin image is here:

![image](https://user-images.githubusercontent.com/34536334/130178738-b8191cd1-5298-4f62-9599-7b93b81cb5e3.png)

**Comment by blindpirate** [comment]
Thanks, will fix.

**Comment by blindpirate** [comment]
Fixed in https://github.com/ByteLegend/ByteLegend/commit/cb586dab1325c75f4554649b4008df018f333184
