### ISSUE TITLE
dead link to `.docs/<lang>/<prefix>developer-guide.md`

### ISSUE THREAD

**Issue by muzimuzhi** [ByteLegend/ByteLegend#31]
In`README`, at the end of section "Start locally", files `.docs/<lang>/<prefix>developer-guide.md` are linked, but the corresponding files were deleted in https://github.com/ByteLegend/ByteLegend/commit/2166e3f16d5a4823d9dcc5db8dbb3b02cd9d719b.

https://github.com/ByteLegend/ByteLegend/blob/9bc60f06c6d19df36acf4a4ff699da7eb5fd5238/README.md#L70

https://github.com/ByteLegend/ByteLegend/blob/9bc60f06c6d19df36acf4a4ff699da7eb5fd5238/README.md#L131

It seems the contents of desired developer guides has been in multiple contribution guides, and since the entrances to those guides are already mentioned in section "Contributing", I suggest the links to the old developer guides could be safely removed from `README`.

**Comment by blindpirate** [comment]
Closed by https://github.com/ByteLegend/ByteLegend/commit/4ac978eefb5ad05bceece4cb3e9d788186556bb2

Thanks for reporting.
