### ISSUE TITLE
无法通过第一个NPC

### ISSUE THREAD

**Issue by gtn1024** [ByteLegend/ByteLegend#46]
不知道这是不是BUG，我记得几个月前时可以通过的。

现在吧门堵住了 😅

![image](https://user-images.githubusercontent.com/69113276/132875750-4bd5418c-fd86-43ba-a425-ee432c96dc1b.png)

**Comment by blindpirate** [comment]
中间删过一次档，你去酒吧里看一下，install-java的任务完成了么？

**Comment by gtn1024** [comment]
![image](https://user-images.githubusercontent.com/69113276/132876794-1943b679-a441-4fa8-bcff-aea3c14ab48e.png)

**Comment by blindpirate** [comment]
请刷新页面然后去老头那儿。

**Comment by gtn1024** [comment]
it works!

**Comment by blindpirate** [comment]
数据库有些不一致，我手动修复了
