### ISSUE TITLE
Optimizing the page of tutorials

### ISSUE THREAD

**Issue by gtn1024** [ByteLegend/ByteLegend#49]
![image](https://user-images.githubusercontent.com/69113276/133014694-31b71fcf-ef22-4fad-bd0a-1a2f159e5758.png)

The pictures here seems too large.

BTW, does it support to use **relative path** for one picture in a Markdown File

**Comment by blindpirate** [comment]
You have two options:

- https://stackoverflow.com/questions/14675913/changing-image-size-in-markdown
- We're using `react-markdown`: https://github.com/remarkjs/react-markdown and try to do something with it.

> BTW, does it support to use relative path for one picture in a Markdown File

No.

**Comment by gtn1024** [comment]
We may add `max-width: 100%;` to `img` element in css.
