### ISSUE TITLE
进咖啡馆就不见人了

### ISSUE THREAD

**Issue by can-not-code** [ByteLegend/ByteLegend#54]
进咖啡馆就不见人了。。。

**Comment by can-not-code** [comment]
而且jdk的那个问题还有移步到附近。。。

**Comment by gtn1024** [comment]
你要走到附近，然后点进去

**Comment by can-not-code** [comment]
> 你要走到附近，然后点进去

谢谢，一定要点那个门。。。

**Comment by gtn1024** [comment]
If it is solved, please **close** this issue.

![image](https://user-images.githubusercontent.com/69113276/133224953-b9dcf511-546a-4ffa-84eb-55651a273710.png)
