### ISSUE TITLE
安装ide的那个问题好像bug了

### ISSUE THREAD

**Issue by can-not-code** [ByteLegend/ByteLegend#55]

**Comment by gtn1024** [comment]
Show the details, 是想让我们臆想么

**Comment by can-not-code** [comment]
> Show the details, 是想让我们臆想么

我看不到题目和教程(也有可能是我github加速的问题)

**Comment by gtn1024** [comment]
> > Show the details, 是想让我们臆想么
> 
> 我看不到题目和教程(也有可能是我github加速的问题)

IDE那个 @blindpirate 已经写好了，但是还没release

**Comment by gtn1024** [comment]
详见 [https://github.com/ByteLegend/game-data/blob/master/JavaIsland/i18n.yml#L972-L990](https://github.com/ByteLegend/game-data/blob/master/JavaIsland/i18n.yml#L972-L990)

**Comment by blindpirate** [comment]
这个关卡还在开发中，稍后会上线。

**Comment by blindpirate** [comment]
IDE的关卡已经部署。
