### ISSUE TITLE
获取咖啡那里无法打开回复框

### ISSUE THREAD

**Issue by jintaojt6** [ByteLegend/ByteLegend#59]
在福报酒吧里无法打开提示框输入jdk版本答案

**Comment by gtn1024** [comment]
图please

**Comment by blindpirate** [comment]
你是否看到了警告“要回答问题，走到相邻的格子里”？

**Comment by blindpirate** [comment]
你需要先走到酒吧里，才能使用酒吧的咖啡机。

**Comment by blindpirate** [comment]
See https://github.com/ByteLegend/ByteLegend/commit/d55c15a77899fbc5bc6d32dcc9748c25d39b5e38
