### ISSUE TITLE
java咖啡任务做完了，但是老头不走

### ISSUE THREAD

**Issue by fbicirno** [ByteLegend/ByteLegend#74]
![image](https://user-images.githubusercontent.com/50105857/135700984-cc643c03-c807-4f06-b12d-301f958a4198.png)
![image](https://user-images.githubusercontent.com/50105857/135700991-c25ce9bd-b600-455f-96c9-dd931f6f8175.png)
你看着现在哪有咖啡啊，

**Comment by blindpirate** [comment]
感谢报告，我手动在数据库里修正了这个问题，具体问题还要看日志确定。

**Comment by blindpirate** [comment]
Fixed in b3e35af63b67f10e9e80fcf0502fece0d70d1c4c

**Comment by MeikleH** [comment]
我昨天也遇到了，但现在还卡在这里，我甚至把PR那个任务都做了XD

**Comment by blindpirate** [comment]
@MeikleH 请重试，我也把你的数据库记录修正了。
