### ISSUE TITLE
【pr修复bug】没有挑战可做，卡关

### ISSUE THREAD

**Issue by fbicirno** [ByteLegend/ByteLegend#75]
![Snipaste_2021-10-05_20-10-34](https://user-images.githubusercontent.com/50105857/136020163-a53375bd-f29c-4170-a3a3-74603c58573c.png)
![Snipaste_2021-10-05_20-10-40](https://user-images.githubusercontent.com/50105857/136020183-bed7b4e7-4779-4989-83f4-a593dddfeacb.png)

**Comment by gtn1024** [comment]
等待更新
