### ISSUE TITLE
创建类挑战无法PR成功

### ISSUE THREAD

**Issue by kangming06** [ByteLegend/ByteLegend#83]
看了历史的PR好像没有通过的。。
![image](https://user-images.githubusercontent.com/74850890/139569932-fdb5faeb-71a5-4d3b-8433-3b48a619b364.png)
![image](https://user-images.githubusercontent.com/74850890/139569938-cc06bdcf-0a7e-49d5-bcbc-fa03c7f451c0.png)

**Comment by gtn1024** [comment]
请看清题目要求

![image](https://user-images.githubusercontent.com/69113276/139570032-11dadd16-bbcb-405d-93f1-46569b7aef00.png)
